import { VerticalBox , HorizontalBox, Button} from "std-widgets.slint";
import { BorderlessWindow } from "borderless-window.slint";

export component Main inherits BorderlessWindow {
    title: "😀你好，Slint！";
    preferred-width: 480px;
    preferred-height: 320px;

    callback close-window();
    callback minimized-window(bool);
    callback maximized-window(bool);
    callback move-window(length, length);
    callback mouse-down(int, int);
    callback mouse-move(int, int);

    on-close-window() => {
        close-window();
    }

    on-minimized-window(enable) => {
        minimized-window(enable);
    }

    on-maximized-window(enable) => {
        maximized-window(enable);
    }

    on-move-window(offset-x, offset-y) => {
        move-window(offset-x, offset-y);
    }
    

    Text {
        color: #2a2a2a;
        text: "Hello World!";
    }
}