
export component BorderlessWindow inherits Window{
    no-frame: true;
    min-width: 200px;
    min-height: 200px;

    in property <brush> title-background: transparent;
    in property <brush> content-background: #fdfdfd;
    in property <brush> title-text-color: white;
    in property <string> parent;
    in property <length> border-width: 4px;
    in property <brush> border-color: #454158;

    property <bool> drag-area-pressed: false;
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;
    
    callback close();
    callback move(length, length);

    function resize-window(width: length, height: length) {
        if(width < root.min-width){
            root.width = root.min-width;
        }else{
            root.width = width;
        }
        if(height < root.min-height){
            root.height = root.min-height;
        }else{
            root.height = height;
        }
    }

    function drag-area-mouse-move(idx: int, x: length, y: length) {
        //拖动窗口
        if (idx == 0){
            if(x != drag-area-down-x && y != drag-area-down-y){
                move(x - drag-area-down-x, y - drag-area-down-y);
            }
        }else if (idx == 1){
            //上边框
            move(0, y - drag-area-down-y);
            resize-window(0, root.height - (y - drag-area-down-y));
        }else if (idx == 2){
            //右边框
            resize-window(root.width + (x - drag-area-down-x), root.height);
        }else if (idx == 3){
            //下边框
            resize-window(root.width, root.height + (y - drag-area-down-y));
        }else if (idx == 4){
            //左边框
            move(x - drag-area-down-x, 0);
            resize-window(root.width - (x - drag-area-down-x), root.height);
        }else if (idx == 5){
            //左上角
            move(x - drag-area-down-x, y - drag-area-down-y);
            resize-window(root.width - (x - drag-area-down-x), root.height - (y - drag-area-down-y));
        }else if (idx == 6){
            //右上角
            move(0, y - drag-area-down-y);
            resize-window(root.width + (x - drag-area-down-x), root.height - (y - drag-area-down-y));
        }else if (idx == 7){
            //右下角
            resize-window(root.width + (x - drag-area-down-x), root.height + (y - drag-area-down-y));
        }else if (idx == 8){
            //左下角
            move(x - drag-area-down-x, 0);
            resize-window(root.width - (x - drag-area-down-x), root.height + (y - drag-area-down-y));
        }
    }

    function drag-area-mouse-event(idx: int, ev: PointerEvent, x: length, y: length) {
        drag-area-pressed = ev.kind == PointerEventKind.down;
        drag-area-down-x = x;
        drag-area-down-y = y;
    }

    // 上边框点击区域
    top-border-touch:= TouchArea{
        mouse-cursor: row-resize;
        width: 100%;
        height: root.border-width;
        x: 0;
        y: 0;
        moved => {
            drag-area-mouse-move(1, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(1, ev, self.mouse-x, self.mouse-y);
        }
    }
    
    // 右边框点击区域
    right-border-touch:= TouchArea{
        mouse-cursor: col-resize;
        width: root.border-width;
        height: 100%;
        x: root.width - root.border-width;
        y: 0;
        moved => {
            drag-area-mouse-move(2, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(2, ev, self.mouse-x, self.mouse-y);
        }
    }

    // 下边框点击区域
    bottom-border-touch:= TouchArea{
        mouse-cursor: row-resize;
        width: 100%;
        height: root.border-width;
        x: 0;
        y: root.height - root.border-width;
        moved => {
            drag-area-mouse-move(3, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(3, ev, self.mouse-x, self.mouse-y);
        }
    }

    // 左边框点击区域
    left-border-touch:= TouchArea{
        mouse-cursor: col-resize;
        width: root.border-width;
        height: 100%;
        x: 0;
        y: 0;
        moved => {
            drag-area-mouse-move(4, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(4, ev, self.mouse-x, self.mouse-y);
        }
    }

    // 左上角点击区域
    left-top-border-touch:= TouchArea{
        mouse-cursor: nw-resize;
        width: root.border-width;
        height: root.border-width;
        x: 0;
        y: 0;
        moved => {
            drag-area-mouse-move(5, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(5, ev, self.mouse-x, self.mouse-y);
        }
    }
    // 右上角点击区域
    right-top-border-touch:= TouchArea{
        mouse-cursor: sw-resize;
        width: root.border-width;
        height: root.border-width;
        x: root.width - root.border-width;
        y: 0;
        moved => {
            drag-area-mouse-move(6, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(6, ev, self.mouse-x, self.mouse-y);
        }
    }
    //右下角点击区域
    right-bottom-border-touch:= TouchArea{
        mouse-cursor: nw-resize;
        width: root.border-width;
        height: root.border-width;
        x: root.width - root.border-width;
        y: root.height - root.border-width;
        moved => {
            drag-area-mouse-move(7, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(7, ev, self.mouse-x, self.mouse-y);
        }
    }
    //左下角点击区域
    left-bottom-border-touch:= TouchArea{
        mouse-cursor: sw-resize;
        width: root.border-width;
        height: root.border-width;
        x: 0;
        y: root.height - root.border-width;
        moved => {
            drag-area-mouse-move(8, self.mouse-x, self.mouse-y);
        }
        pointer-event(ev) => {
            drag-area-mouse-event(8, ev, self.mouse-x, self.mouse-y);
        }
    }

    VerticalLayout {
        padding: root.border-width;
        //标题栏
        Rectangle {
            height: 28px;
            background: title-background;
            HorizontalLayout {
                padding-right: 7px;
                padding-left: 7px;
                //标题
                Text {
                    text: root.title;
                    color: title-text-color;
                    vertical-alignment: center;
                    TouchArea {
                        moved => {
                            drag-area-mouse-move(0, self.mouse-x, self.mouse-y);
                        }
                        pointer-event(ev) => {
                            drag-area-mouse-event(0, ev, self.mouse-x, self.mouse-y);
                        }
                    }
                }
                //关闭按钮
                Rectangle {
                    y: 7px;
                    border-radius: 3px;
                    width: 14px;
                    height: 14px;
                    background: root.border-color;
                    touch := TouchArea {
                        clicked => { close() }
                    }
                    Text {
                        color: touch.has-hover? touch.pressed? gray: title-text-color : lightgray;
                        text: "×";
                    }
                }
            }
        }
        Rectangle {
            background: content-background;
            @children
        }
    }
}